// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using TeacherBackend.Data;

namespace TeacherBackend.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    internal class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TeacherBackend.Model.Lesson", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy",
                        SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<int?>("LessonSubjectId")
                    .HasColumnType("int");

                b.Property<int>("Minutes")
                    .HasColumnType("int");

                b.Property<string>("Name")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Price")
                    .HasColumnType("int");

                b.Property<DateTime>("StartTime")
                    .HasColumnType("datetime2");

                b.Property<int?>("StudentId")
                    .HasColumnType("int");

                b.Property<int?>("TeacherId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("LessonSubjectId");

                b.HasIndex("StudentId");

                b.HasIndex("TeacherId");

                b.ToTable("Lessons");
            });

            modelBuilder.Entity("TeacherBackend.Model.LessonSubject", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy",
                        SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("Name")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Price")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.ToTable("LessonSubject");
            });

            modelBuilder.Entity("TeacherBackend.Model.UserModel", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy",
                        SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<int>("Age")
                    .HasColumnType("int");

                b.Property<string>("Email")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Password")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("UserName")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("UserType")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.ToTable("Users");
            });

            modelBuilder.Entity("TeacherBackend.Model.Lesson", b =>
            {
                b.HasOne("TeacherBackend.Model.LessonSubject", "LessonSubject")
                    .WithMany()
                    .HasForeignKey("LessonSubjectId");

                b.HasOne("TeacherBackend.Model.UserModel", "Student")
                    .WithMany()
                    .HasForeignKey("StudentId");

                b.HasOne("TeacherBackend.Model.UserModel", "Teacher")
                    .WithMany()
                    .HasForeignKey("TeacherId");
            });
#pragma warning restore 612, 618
        }
    }
}